dist: xenial
sudo: false
env:
  global:
    - secure: "sc3DIqa9jvrSGUe2/y3AL2B1R+vGCVnoF+ynWrVdESr7SIQRHmTj1yd4QIZg2kCyvqJKyaRKvItZ/fJwDfuBWDe+/DgdxCWmjdCmLuoBaAFp6fc4TVCmcr+vp3eWOmgOanAyT/xb4+WjO33OiKTzKa25eGLueU4Oj+1ER4hw+LWtEKj6/57Ib6fPc6X+9TStZz9JGlWtuQLUYR37H6KBNGFpsLvpOrPAts/Ul5VGjKcf9Vz8Xo06YtsbCQpIXZdvPud7BistK8O5SityuEE6RDcCBhrShe4ohaLJLmnja40ZmOvgEH8dF5nBlA9c+lfyNuk0k47fT07Bady/qe0fna0WvUtFi/Q04LDU04uAeSwm6TyM7et6bwh7WcnY0PDD6alBkizTaeL0hTtfJ5nPXlR/4f9UvLidmwIqlNlm+BL8oQO2Mm1Yfz5KH8HzLlHjHYqaU0MRvkzfd+/mW2G1ZQ84WpqacWL58jooUHdDupQQ4UD9U4BGaBfauRKmTJ9jbGEnOqrSybenHLfJph+iVfvGCbD9N2gk+y/GNbzsGLZkitBPL3GEOSUP/gH63Ex7WyejP9eaQFjrAlvluqULeZWRHNHipThX+pD5+zzSh2zroO8Z7Hy3iF2FctCCCdpDcC++nfjgW0DQuHldF9fZABYsaNy5ZX2jduX/Ch5sBI4=" # BINTRAY_API_KEY
jobs:  
  include:
    - stage: "Build application directory"
      language: java
      jdk: openjdk11
      before_script:
        - |
          if [[ -n "${TRAVIS_TAG}" ]]; then
            curl -o buildkit.zip -L https://dl.bintray.com/cryptomator/cryptomator/${TRAVIS_TAG}/buildkit-linux.zip
          else
            curl -o buildkit.zip -L https://dl.bintray.com/cryptomator/cryptomator/snapshot/buildkit-linux.zip
          fi
        - unzip buildkit.zip
      script: 
        - ./appdir-build.sh
      before_deploy:
        - export TODAY=`date +'%Y-%m-%d'`; envsubst '$TRAVIS_TAG $TODAY' < appdir-deploy-release.tmpl.json > appdir-deploy-release.json
      deploy:
      - provider: bintray
        file: appdir-deploy-snapshot.json
        user: cryptobot
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          repo: cryptomator/cryptomator-linux
          all_branches: true
          tags: false
      - provider: bintray
        file: appdir-deploy-release.json
        user: cryptobot
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          repo: cryptomator/cryptomator-linux
          tags: true
    - stage: "Package as AppImage"
      addons:
        apt:
          packages:
          - appstream
          - tree
      install:
        - curl -L https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage -o ./tools/appimagekit/appimagetool.AppImage
        - chmod +x ./tools/appimagekit/appimagetool.AppImage
        - (cd ./tools/appimagekit && ./appimagetool.AppImage --appimage-extract)
      before_script:
        - |
          if [[ -n "${TRAVIS_TAG}" ]]; then
            curl -o appdir.tar.gz -L https://dl.bintray.com/cryptomator/cryptomator/${TRAVIS_TAG}/appdir.tar.gz
          else
            curl -o appdir.tar.gz -L https://dl.bintray.com/cryptomator/cryptomator/snapshot/appdir.tar.gz
          fi
        - tar -xzvf appdir.tar.gz;
      script: 
        - ./appimage-build.sh ${TRAVIS_TAG}
      before_deploy:
        - export TODAY=`date +'%Y-%m-%d'`; envsubst '$TRAVIS_TAG $TODAY' < appimage-deploy-release.tmpl.json > appimage-deploy-release.json
      deploy:
      - provider: bintray
        file: appimage-deploy-snapshot.json
        user: cryptobot
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          repo: cryptomator/cryptomator-linux
          all_branches: true
          tags: false
      - provider: bintray
        file: appimage-deploy-release.json
        user: cryptobot
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          repo: cryptomator/cryptomator-linux
          tags: true
